spring:
  thymeleaf:
    cache: false
    encoding: utf-8
    mode: HTML5
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/blog?characterEncodi=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
    #data: classpath:import.sql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true