spring:
  thymeleaf:
    cache: false
    encoding: utf-8
    mode: HTML5
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/blog?characterEncodi=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
    data: classpath:sql/import.sql
    initialization-mode: always
    #schema: classpath:sql/schema.sql
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
      cluster-name: elasticsearch
blog:
  es:
    host: 127.0.0.1:9200